#!/bin/sh -e

mkdir -pv build

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Ddefault_library=both \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-x11=false \
    -Denable-xkbregistry=false \
    build

ninja -C build
DESTDIR=$1 ninja -C build install
