#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

make
make DESTDIR="$1" install

mkdir -pv $1/etc/sv/eiwd
cp iwd_passphrase $1/usr/bin
cp eiwd.run $1/etc/sv/eiwd/run
ln -s /run/runit/supervise.eiwd $1/etc/sv/eiwd/supervise
