#!/bin/sh -e

mkdir -pv build

meson setup \
    -Dprefix=/usr \
    -Dtee=enabled \
    -Dxcb=disabled \
    -Dxlib=disabled \
    -Dxlib-xcb=disabled \
    -Dtests=disabled \
    -Dspectre=disabled \
    build

ninja -C build
DESTDIR=$1 ninja -C build install
