#!/bin/sh -e

mkdir -pv build

meson setup \
    -Dprefix=/usr \
    -Dgtk_doc=false \
    -Dxft=disabled \
    -Dintrospection=disabled \
    -Dcairo=enabled \
    build

ninja -C build
DESTDIR=$1 ninja -C build install
