#!/bin/sh -e

mkdir -pv build

meson setup \
    -Dprefix=/usr \
    build

ninja -C build
DESTDIR=$1 ninja -C build install

# Set suid on seatd-launch.
chmod u+s "$1/usr/bin/seatd-launch"

# Install runit service.
mkdir -p "$1/etc/sv/seatd"
cp -f seatd.run "$1/etc/sv/seatd/run"
ln -sf /run/runit/supervise.seatd "$1/etc/sv/seatd/supervise"
