#!/bin/sh -e

patch -p1 < boolcodes.patch

./configure --prefix=/usr \
    --enable-function-subdirs \
    --enable-fndir=/usr/share/zsh/functions \
    --enable-runhelpdir=/usr/share/zsh/help \
    --enable-scriptdir=/usr/share/zsh/scripts \
    --enable-additional-fpath=/usr/share/zsh/vendor-completions \
    --disable-gdbm

make
make DESTDIR=$1 install

install -Dm644 zprofile $1/etc/zprofile
